# Numpy


Numerical Python is an open source library in Python.

- Vector processing

In [41]:
# !pip install numpy


# Single Dimension numpy array

In [42]:
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [43]:
type(n1)

numpy.ndarray

# Multi dimension numpy array

In [44]:
n2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
n2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [45]:
n2.shape

(3, 3)

# initializing numpy arrays with zeros

In [46]:
n3 = np.zeros((9,9))
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initializing a array of matrix with full then

In [47]:
n4 = np.full((9,9),6)
n4

array([[6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [48]:
n4[3][3] = 3
n4[3]

array([6, 6, 6, 3, 6, 6, 6, 6, 6])

# Initialization of NumPy array within a range

In [49]:

n5=np.arange(10,1)
n5 

array([], dtype=int64)

# initializing NumPy array with the random numbers

In [50]:
RandomArray = np.random.randint(0,((10000000000000),10)
RandomArray

SyntaxError: '(' was never closed (2267804126.py, line 1)

# initialization the array shape changes in a fracion of seconds.

In [ ]:
n8 =np.array([[10,20,30],[20,30,40],[40,50,60],[60,70,80]])
n8.shape

(4, 3)

In [ ]:
n8.shape = (3,4)

In [ ]:
n8.shape
n8

array([[10, 20, 30, 20],
       [30, 40, 40, 50],
       [60, 60, 70, 80]])

In [ ]:
n8.T

array([[10, 30, 60],
       [20, 40, 60],
       [30, 40, 70],
       [20, 50, 80]])

# Joining the numpy Array


In [ ]:
a = np.array((1,10))
b = np.array((1,10))
c = np.array((1,10))
d= np.array((1,10))

a = np.random.randint(0,1000,10)
b = np.random.randint(0,1000,10)
c = np.random.randint(0,1000,10)
d = np.random.randint(0,1000,10)

In [ ]:
vertical_stack = np.vstack((a,b,c,d))
horizontal_stack = np.hstack((a,b,c,d))
column_stack = np.column_stack((a,b,c,d))
vertical_stack.shape

(4, 10)

In [ ]:
# makes multi dimnesional array

vertical_stack

array([[715, 769, 613, 628,  43, 234, 516, 324, 565, 797],
       [303, 654, 725, 380, 643, 782, 730, 107,   6, 850],
       [931, 759, 158, 727, 472, 721, 415, 808, 497, 231],
       [753, 546, 756, 520, 764, 306,  99,  32, 190, 688]])

In [ ]:
# makes single dim array

horizontal_stack

array([715, 769, 613, 628,  43, 234, 516, 324, 565, 797, 303, 654, 725,
       380, 643, 782, 730, 107,   6, 850, 931, 759, 158, 727, 472, 721,
       415, 808, 497, 231, 753, 546, 756, 520, 764, 306,  99,  32, 190,
       688])

In [ ]:
# makes mulit dim but with zeroth index elements
column_stack

array([[715, 303, 931, 753],
       [769, 654, 759, 546],
       [613, 725, 158, 756],
       [628, 380, 727, 520],
       [ 43, 643, 472, 764],
       [234, 782, 721, 306],
       [516, 730, 415,  99],
       [324, 107, 808,  32],
       [565,   6, 497, 190],
       [797, 850, 231, 688]])

In [ ]:
horizontal_stack.shape

(40,)

In [ ]:
vertical_stack.shape


(4, 10)

In [ ]:
column_stack.shape


(10, 4)

# Numpy intersection, differences and union

In [ ]:
x = np.array([x for x in range(10,70,10)])
x

array([10, 20, 30, 40, 50, 60])

In [ ]:
y = np.array([i for i in range(30,170,20)])
y

array([ 30,  50,  70,  90, 110, 130, 150])

In [ ]:
np.intersect1d(x,y)

array([30, 50])

In [ ]:
np.union1d(x,y)

array([ 10,  20,  30,  40,  50,  60,  70,  90, 110, 130, 150])

In [ ]:
np.setdiff1d(x,y)

array([10, 20, 40, 60])

In [ ]:
np.setdiff1d(y,x)

array([ 70,  90, 110, 130, 150])

In [ ]:
t = np.array([10,20])
s =np.array([30,40])

np.sum([t,s],axis=1)

array([30, 70])

# NumPy array mathematics

In [ ]:
p  = np.array([x for x in range(10,40,10)])

In [ ]:
p +1

array([11, 21, 31])

In [ ]:
p -1

array([ 9, 19, 29])

In [ ]:
p*1

array([10, 20, 30])

In [ ]:
p ** 2

array([100, 400, 900])

In [ ]:
p // 4

array([2, 5, 7])

In [ ]:
p ** p

array([         10000000000, -2101438300051996672,  2565992168703393792])

# NumPy maths functions

In [ ]:
nn = np.array([i for i in range(10,60,10)])

In [ ]:
nn[-1] = 1000
nn

array([  10,   20,   30,   40, 1000])

* When there is missing values we use mean,median, interpolation, correlation regression techniques to fill the missing value.
* Also for outliers we assume the value using above techniques

In [ ]:
nn.mean()

30.0

In [ ]:
np.median(nn)

30.0

In [ ]:
np.std(nn)

390.1281840626232

In [ ]:
np.cov(nn)

array(190250.)

In [ ]:
np.var(nn)

152200.0

In [ ]:
np.min(nn)

10

In [ ]:
np.count_nonzero(nn)

5

In [ ]:
np.max(nn)

1000

# saving and loading the NumPy array

In [ ]:
krishom_num = np.array([x for x in range(10,100,10)])

In [51]:
np.save('krishom',krishom_num)

In [52]:
np.load('krishom.npy')

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
np.random.uniform(size=10)

array([0.5129918 , 0.86502202, 0.43230795, 0.89958963, 0.6050881 ,
       0.71814576, 0.20899177, 0.06298484, 0.40950024, 0.03311088])

In [59]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Einstein Smmation Conventions

* used to compute many multi dim and linear algebric operation on arrays

In [60]:
a = np.array([x for x in range(10,100,10)]).reshape(3,3)
a


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [62]:
b = np.array([x for x in range(1,10)]).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.einsum('ii->i',a)

array([10, 50, 90])

In [70]:
# transpose
np.einsum('ij->ji',a)

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [69]:
#multiplication
np.einsum('ij,ji',a,b)

2610

In [71]:
np.percentile(nn,0.5)

10.2

In [73]:
np.quantile(nn,0.25)

20.0

In [74]:
# Matrix-Vector Multiplication
A = np.array([[1,2],[3,4],[5,6]])
x = np.array([7,8])

np.einsum('ij,j->i',A,x)

array([23, 53, 83])